platform :ios, "11.2"
use_modular_headers!

project 'TokenCore.xcodeproj'
target 'TokenCore_Example' do
  
  pod 'TokenCore', :path => '../'
  pod 'PureLayout'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Alamofire', '~> 5.0.0-beta.2'
  pod "TokenCoreDep", :path => '../../token-core-ios-dep'

#  pod "TokenCore", git: "https://github.com/consenlabs/token-core-ios.git"
end
